{ lib, inputs, ... }:

{
  mkUser = { username, stateVersion, system ? "x86_64-linux", hostname ? null }:
    lib.homeManagerConfiguration {
      pkgs = lib.pkgsForSystem system;

      extraSpecialArgs = {
        inherit inputs username system hostname stateVersion;

        # TODO: Find a way to merge with lib generated by lib.homeManagerConfiguration
        lib' = lib;
      };

      modules = [
        ../users/${username}/home.nix

        (import ../modules/home-manager/system-config-support.nix {
          inherit lib;
        })
      ];
    };
}
