{ lib, inputs, hostname, system, stateVersion, users ? [ ], ... }:

{
  home-manager = {
    users =
      lib.genAttrs users (username: import ../../users/${username}/home.nix);

    sharedModules = [
      (import ../common/nixpkgs.nix { inherit lib; })
      (import ../home-manager/system-config-support.nix { inherit lib; })
    ];

    extraSpecialArgs = {
      inherit inputs system hostname stateVersion;

      # TODO: Find a way to merge with lib generated by lib.homeManagerConfiguration
      lib' = lib;
    };

    # https://discourse.nixos.org/t/home-manager-useuserpackages-useglobalpkgs-settings/34506/4
    useGlobalPkgs = false;
    useUserPackages = false;
  };
}
